version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MotiMeStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-135vb4rppdxb3"
s3_prefix = "MotiMeStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
